owner: Tanic-Labs
repo: termo-status

sites:
  - name: API
    url: https://api.termo.ai/health
    expectedStatusCodes:
      - 200

  - name: Web
    url: https://termo.ai
    expectedStatusCodes:
      - 200
      - 301

  - name: Database
    url: https://idriogxxzalrnlqrwooo.supabase.co/rest/v1/
    expectedStatusCodes:
      - 200
      - 401

  - name: Agents
    url: https://api.sprites.dev/v1
    expectedStatusCodes:
      - 200
      - 401

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"

i18n:
  activeIncidents: Active incidents
  allSystemsOperational: All systems operational
  incidentReport: "Incident Report for $DATE"

commitMessages:
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  degradedPerformance: "$SITE_NAME has degraded performance ($RESPONSE_TIME ms)"
